# Numpy Library

## One dimensional Array

In [84]:
import numpy as np

In [85]:
original_list = [12.23, 13.32, 100, 36.32]
one_d_array = np.array(original_list)
print(one_d_array)

[ 12.23  13.32 100.    36.32]


## 3x3 matrix range(2,10)

In [86]:
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## Null vector of size 10

In [87]:
x = np.zeros(10)
print(x)
print("Update sixth index value to 11")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth index value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


## Reverse an array

In [88]:
original_array = np.arange(12,38)
print(original_array)
reverse_array = original_array[::-1]
print(reverse_array)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


## 2d array with one on border and 0 inside

In [89]:
original_array = np.ones(25).reshape(5,5)
print(original_array)
original_array[1:-1,1:-1] = 0
print("Printing one on side zero inside")
print(original_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Printing one on side zero inside
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Add 0 to the border on 1s array of 3x3

In [90]:
original_array = np.ones((3,3))
print(original_array)
print("Printing zero on the borders of array")
original_array = np.pad(original_array, pad_width=1, mode='constant', constant_values=0)
print(original_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Printing zero on the borders of array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## Checkboard Pattern

In [91]:
board = np.zeros((8,8),dtype=int)
board[::2,1::2] = 1
board[1::2,::2] = 1
print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Convert list tuple to arrays

In [92]:
list_input = [1,2,3,4,5]
array_1 = np.array(list_input)
print(array_1)
tuple_input = (1,2,3,4,5)
array_2 = np.array(tuple_input)
print(array_2)

[1 2 3 4 5]
[1 2 3 4 5]


## Append values at the end

In [93]:
original_list = [10,20,30]
print()
appended_array = np.append(original_list,[40,50,60,70,80,90])
print(appended_array)


[10 20 30 40 50 60 70 80 90]


In [94]:
x= np.array([ 1.00000000+0.j, 0.70710678+0.70710678j])
print(x)
print("Real and imaginary part")
print(x.real,x.imag)

[1.   +0.j    0.707+0.707j]
Real and imaginary part
[1.    0.707] [0.    0.707]


In [95]:
x = np.array([1,2,3],dtype=np.int64)
print("Size of the array: ", x.size)
print("Length of one array element in bytes: ", x.itemsize)
print("Total bytes consumed by the elements of the array: ", x.nbytes)

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


## Common values between two array

In [96]:
x = np.array([0,10,20,40,60])
y = np.array([10,30,40])
print(x,y)
common_values = np.intersect1d(x,y)
print("The common values are :")
print(common_values)

[ 0 10 20 40 60] [10 30 40]
The common values are :
[10 40]


## Difference between two arrays

In [97]:
x = np.array([0,10,20,40,60,80])
y = np.array([10, 30, 40, 50, 70, 90])
print(x,y)
difference = np.setdiff1d(y,x)
print(difference)

[ 0 10 20 40 60 80] [10 30 40 50 70 90]
[30 50 70 90]


## Set exclusive or

In [98]:
x = np.array([ 0, 10, 20, 40, 60, 80])
y = np.array([10, 30, 40, 50, 70])
print(x,y)
exclusive_set = np.setxor1d(x,y)
print(exclusive_set)

[ 0 10 20 40 60 80] [10 30 40 50 70]
[ 0 20 30 50 60 70 80]


## Comparing two arrays

In [99]:
x = np.array([1,2])
y = np.array([4,5])
print(x>y)
print(x>=y)
print(x<y)
print(x<=y)

[False False]
[False False]
[ True  True]
[ True  True]


## numpy array to text file

In [100]:
x = np.array([1,2,3,4,5])
print(x)
with open("file.txt","w") as file:
    file.write(str(x))
print("Array saved in file")

[1 2 3 4 5]
Array saved in file


## Array flattening

In [101]:
x = np.array([[10,20,30],[20,40,50]])
print(x)
flattened_arr = x.flatten()
print(flattened_arr)

[[10 20 30]
 [20 40 50]]
[10 20 30 20 40 50]


## Changing data type of an array

In [102]:
x = np.array([[2,4,6],[6,8,10]],dtype=np.int32)
print(x)
print("Changing the data type to float64")
y = np.array(x, dtype = np.float64)
print(y)
print("Another way")
print(x.astype(np.float64))

[[ 2  4  6]
 [ 6  8 10]]
Changing the data type to float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]
Another way
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


## Inserting 1 at the diagonal and other places zero

In [103]:
x = np.zeros((3,3))
print("one way")
for i in range(len(x)):
    for j in range(i+1):
        if i == j:
            x[i,j] = 1
print(x)
print("Another way")
y = np.eye(3)
print(y)

one way
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Another way
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [104]:
## Making a trigonal matrix

In [105]:
x = np.tri(4,3,1)
print(x)

[[1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Concatenate two dimensional array

In [106]:
a = np.array([[0, 1, 3], [5, 7, 9]])
print(a)
b = np.array([[0, 2, 4], [6, 8, 10]])
print(b)
print("The concatenated array is ")
x =np.concatenate((a,b),axis = 1)
print(x)

[[0 1 3]
 [5 7 9]]
[[ 0  2  4]
 [ 6  8 10]]
The concatenated array is 
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


## Making the array immutable

In [107]:
x = np.zeros(10)
x.flags.writeable = False
print("Test the array is read-only or not:")
print("Try to change the value of the first element:")
x[0] = 1

Test the array is read-only or not:
Try to change the value of the first element:


ValueError: assignment destination is read-only

## Multiplying every element of array by 3

In [108]:
x = np.arange(0,12).reshape(3,4)
x = x * 3
print(x)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


## Converting arrays to list

In [109]:
x = np.arange(0,6).reshape(3,2)
print(x)
y = list(list(y) for y in x )
print("After converting to list")
print(y)
print("Another way")
z = x.tolist()
print(z)

[[0 1]
 [2 3]
 [4 5]]
After converting to list
[[0, 1], [2, 3], [4, 5]]
Another way
[[0, 1], [2, 3], [4, 5]]


## Printing arrays value with precision

In [110]:
x = np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,
               0.35399976, 0.99469633, 0.0694458, 0.54711478])
np.set_printoptions(precision = 3)
print(x)

[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


## Suppressing the notation

In [111]:
x = np.array([ 1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
print(x)
np.set_printoptions(suppress= True)
print(x)

[   0.       1.6   1200.       0.235]
[   0.       1.6   1200.       0.235]


## Adding extra column in two-d array

In [112]:
x= np.array([[ 10, 20, 30],[ 40, 50, 60]])
y = np.array([[100],[200]])
z = np.concatenate((x,y),axis = 1)
print(z)
print("Another way")
z = np.append(x,y,axis = 1)
print(z)

[[ 10  20  30 100]
 [ 40  50  60 200]]
Another way
[[ 10  20  30 100]
 [ 40  50  60 200]]


## deleting specific index

In [113]:
x = np.arange(10,101,10)
index = [0,3,4]
print(x)
print("After deleting 0th,4th,5th element")
new_x = np.delete(x,index)
print(new_x)

[ 10  20  30  40  50  60  70  80  90 100]
After deleting 0th,4th,5th element
[ 20  30  60  70  80  90 100]
