# Numpy Library


## One dimensional Array


In [154]:
import numpy as np

In [155]:
original_list = [12.23, 13.32, 100, 36.32]
one_d_array = np.array(original_list)
print(one_d_array)

[ 12.23  13.32 100.    36.32]


## 3x3 matrix range(2,10)

In [156]:
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## Null vector of size 10

In [157]:
x = np.zeros(10)
print(x)
print("Update sixth index value to 11")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth index value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


## Reverse an array

In [158]:
original_array = np.arange(12,38)
print(original_array)
reverse_array = original_array[::-1]
print(reverse_array)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


## 2d array with one on border and 0 inside

In [159]:
original_array = np.ones(25).reshape(5,5)
print(original_array)
original_array[1:-1,1:-1] = 0
print("Printing one on side zero inside")
print(original_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Printing one on side zero inside
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Add 0 to the border on 1s array of 3x3

In [160]:
original_array = np.ones((3,3))
print(original_array)
print("Printing zero on the borders of array")
original_array = np.pad(original_array, pad_width=1, mode='constant', constant_values=0)
print(original_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Printing zero on the borders of array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## Checkboard Pattern

In [161]:
board = np.zeros((8,8),dtype=int)
board[::2,1::2] = 1
board[1::2,::2] = 1
print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Convert list tuple to arrays

In [162]:
list_input = [1,2,3,4,5]
array_1 = np.array(list_input)
print(array_1)
tuple_input = (1,2,3,4,5)
array_2 = np.array(tuple_input)
print(array_2)

[1 2 3 4 5]
[1 2 3 4 5]


## Append values at the end

In [163]:
original_list = [10,20,30]
appended_array = np.append(original_list,[40,50,60,70,80,90])
print(appended_array)

[10 20 30 40 50 60 70 80 90]


In [164]:
x= np.array([ 1.00000000+0.j, 0.70710678+0.70710678j])
print(x)
print("Real and imaginary part")
print(x.real,x.imag)

[1.   +0.j    0.707+0.707j]
Real and imaginary part
[1.    0.707] [0.    0.707]


In [165]:
x = np.array([1,2,3],dtype=np.int64)
print("Size of the array: ", x.size)
print("Length of one array element in bytes: ", x.itemsize)
print("Total bytes consumed by the elements of the array: ", x.nbytes)

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


## Common values between two array

In [166]:
x = np.array([0,10,20,40,60])
y = np.array([10,30,40])
print(x,y)
common_values = np.intersect1d(x,y)
print("The common values are :")
print(common_values)

[ 0 10 20 40 60] [10 30 40]
The common values are :
[10 40]


## Difference between two arrays

In [167]:
x = np.array([0,10,20,40,60,80])
y = np.array([10, 30, 40, 50, 70, 90])
print(x,y)
difference = np.setdiff1d(y,x)
print(difference)

[ 0 10 20 40 60 80] [10 30 40 50 70 90]
[30 50 70 90]


## Set exclusive or

In [168]:
x = np.array([ 0, 10, 20, 40, 60, 80])
y = np.array([10, 30, 40, 50, 70])
print(x,y)
exclusive_set = np.setxor1d(x,y)
print(exclusive_set)

[ 0 10 20 40 60 80] [10 30 40 50 70]
[ 0 20 30 50 60 70 80]


## Comparing two arrays

In [169]:
x = np.array([1,2])
y = np.array([4,5])
print(x>y)
print(x>=y)
print(x<y)
print(x<=y)

[False False]
[False False]
[ True  True]
[ True  True]


## numpy array to text file

In [170]:
x = np.array([1,2,3,4,5])
print(x)
with open("file.txt","w") as file:
    file.write(str(x))
print("Array saved in file")

[1 2 3 4 5]
Array saved in file


## Array flattening

In [171]:
x = np.array([[10,20,30],[20,40,50]])
print(x)
flattened_arr = x.flatten()
print(flattened_arr)

[[10 20 30]
 [20 40 50]]
[10 20 30 20 40 50]


## Changing data type of an array

In [172]:
x = np.array([[2,4,6],[6,8,10]],dtype=np.int32)
print(x)
print("Changing the data type to float64")
y = np.array(x, dtype = np.float64)
print(y)
print("Another way")
print(x.astype(np.float64))

[[ 2  4  6]
 [ 6  8 10]]
Changing the data type to float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]
Another way
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


## Inserting 1 at the diagonal and other places zero

In [173]:
x = np.zeros((3,3))
print("one way")
for i in range(len(x)):
    for j in range(i+1):
        if i == j:
            x[i,j] = 1
print(x)
print("Another way")
y = np.eye(3)
print(y)

one way
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Another way
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Making a trigonal matrix

In [174]:
x = np.tri(4,3,-1)
print(x)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


## Concatenate two dimensional array

In [175]:
a = np.array([[0, 1, 3], [5, 7, 9]])
print(a)
b = np.array([[0, 2, 4], [6, 8, 10]])
print(b)
print("The concatenated array is ")
x =np.concatenate((a,b),axis = 1)
print(x)


[[0 1 3]
 [5 7 9]]
[[ 0  2  4]
 [ 6  8 10]]
The concatenated array is 
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


## Making the array immutable

In [176]:
x = np.zeros(10)
x.flags.writeable = False
print("Test the array is read-only or not:")
print("Try to change the value of the first element:")
x[0] = 1

Test the array is read-only or not:
Try to change the value of the first element:


ValueError: assignment destination is read-only

## Multiplying every element of array by 3

In [ ]:
x = np.arange(0,12).reshape(3,4)
x = x * 3
print(x)

## Converting arrays to list

In [ ]:
x = np.arange(0,6).reshape(3,2)
print(x)
y = list(list(y) for y in x )
print("After converting to list")
print(y)
print("Another way")
z = x.tolist()
print(z)

## Printing arrays value with precision

In [ ]:
x = np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,
  0.35399976, 0.99469633, 0.0694458, 0.54711478])
np.set_printoptions(precision = 3)
print(x)

## Suppressing the notation

In [ ]:
x = np.array([ 1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
print(x)
np.set_printoptions(suppress= True)
print(x)

## Adding extra column in two-d array

In [ ]:
x= np.array([[ 10, 20, 30],[ 40, 50, 60]])
y = np.array([[100],[200]])
z = np.concatenate((x,y),axis = 1)
print(z)
print("Another way")
z = np.append(x,y,axis = 1)
print(z)

## deleting specific index

In [ ]:
x = np.arange(10,101,10)
index = [0,3,4]
print(x)
print("After deleting 0th,4th,5th element")
new_x = np.delete(x,index)
print(new_x)

# PANDAS LIBRARY

In [ ]:
import pandas as pd

## Convert list to series data type object

In [ ]:
data = pd.Series([2, 4, 6, 8, 10])
print(data)

## Convert series to python list type object

In [ ]:
data = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(data)
print(type(data))
print("Convert Pandas Series to Python list")
print(data.tolist())
print(type(data.tolist()))

## Arithmetic operations on two panda series

In [ ]:
dataset1 = pd.Series([2, 4, 6, 8, 10])
dataset2 = pd.Series([1, 3, 5, 7, 9])
dataset = dataset1 + dataset2
print("Add two Series:")
print(dataset)
print("Subtract two Series:")
dataset = dataset1 - dataset2
print(dataset)
print("Multiply two Series:")
datatset = dataset1 * dataset2
print(datatset)
print("Divide Series1 by Series2:")
dataset = dataset1 / dataset2
print(dataset)

## Element wise raise to the power in series

In [ ]:
dataset = pd.Series([0, 1, 2, 3, 4, 5, 6])
print(dataset)
print("Raised to the power 3")
dataset = dataset ** 3
print(dataset)

## Convert dictionary to dataframe

In [179]:
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
              'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
              'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
              'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


## info of above dataset

In [180]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10 non-null     object 
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64  
 3   qualify   10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


## get first three row of above dataframe

In [181]:
df.head(3)

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

## Select name and score column

In [182]:
df[["name","score"]]

name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

## Select rows 1,3,5,6 and column 1,3

In [183]:
df.iloc[[1,3,5,6],[1,3]]

score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes

## Select rows where no of attempts > 2

In [184]:
print(df[df.attempts > 2])
print("Another way")
df[df["attempts"]>2]

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes
Another way


name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

## Find the no of rows and column

In [185]:
print(df.shape)

(10, 4)


## Select the rows where score is none

In [186]:
print(df[df["score"].isnull()])

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


## Row where no_of_attempts <2 and score greater than 15

In [187]:
df[(df["attempts"]) < 2 & (df["score"]>15)]

Empty DataFrame
Columns: [name, score, attempts, qualify]
Index: []

## Set score in row d to 11.5

In [188]:
df.loc["d","score"] = 11.5
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

## Calculte sum of attempts

In [189]:
df.attempts.sum()

19

## Calculate mean of scores

In [190]:
df.score.mean()


13.333333333333334

## Adding a new row to the dataframe

In [191]:
df.loc["k"]=["Suresh",15.5,1,"yes"]
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes

## Dropping the k th row

In [192]:
df.drop("k")

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

## Sorting by columns

In [193]:
df.sort_values(by='name', ascending= False)

name  score  attempts qualify
k     Suresh   15.5         1     yes
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes

In [194]:
df.sort_values(by = "score",ascending= True).dropna()

name  score  attempts qualify
i      Kevin    8.0         2      no
b       Dima    9.0         3      no
e      Emily    9.0         2      no
d      James   11.5         3      no
a  Anastasia   12.5         1     yes
g    Matthew   14.5         1     yes
k     Suresh   15.5         1     yes
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
f    Michael   20.0         3     yes

## Replacing values of qualify column to pass or fail

In [197]:
df["qualify"] = df["qualify"].map({"yes":"Pass","no":"Fail"})

In [198]:
df

name  score  attempts qualify
a  Anastasia   12.5         1    Pass
b       Dima    9.0         3    Fail
c  Katherine   16.5         2    Pass
d      James   11.5         3    Fail
e      Emily    9.0         2    Fail
f    Michael   20.0         3    Pass
g    Matthew   14.5         1    Pass
h      Laura    NaN         1    Fail
i      Kevin    8.0         2    Fail
j      Jonas   19.0         1    Pass
k     Suresh   15.5         1    Pass

## deleting column from dataframs

In [199]:
df.pop("attempts")

a    1
b    3
c    2
d    3
e    2
f    3
g    1
h    1
i    2
j    1
k    1
Name: attempts, dtype: int64

## Adding new colour column to the dataframe

In [202]:
df["colour"]=['Red','Blue','Orange','Red','White','White','Blue','Green','Green','Red',"Blue"]

In [203]:
df

name  score qualify  colour
a  Anastasia   12.5    Pass     Red
b       Dima    9.0    Fail    Blue
c  Katherine   16.5    Pass  Orange
d      James   11.5    Fail     Red
e      Emily    9.0    Fail   White
f    Michael   20.0    Pass   White
g    Matthew   14.5    Pass    Blue
h      Laura    NaN    Fail   Green
i      Kevin    8.0    Fail   Green
j      Jonas   19.0    Pass     Red
k     Suresh   15.5    Pass    Blue

## iterate over rows

In [204]:
for index, row in df.iterrows():
    print(row["name"],row["score"])

Anastasia 12.5
Dima 9.0
Katherine 16.5
James 11.5
Emily 9.0
Michael 20.0
Matthew 14.5
Laura nan
Kevin 8.0
Jonas 19.0
Suresh 15.5


## Get list from dataframe column headers

In [208]:
print(list(df.columns.values))

['name', 'score', 'qualify', 'colour']


# MATPLOTLIB